### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by dchapsky** [comron/rmemcached#1]
Hi, 

I'm having a build issue when attempting to install this package with r 2.14, specifically the memcached_return_t type is undeclared. Here's some the output of attempting to install.

checking for libmemcached/memcached.h... yes
checking for memcached_create in -lmemcached... yes
configure: creating ./config.status
config.status: creating src/Makevars
*\* libs
gcc -m64 -std=gnu99 -I/usr/include/R  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FOR
TIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c rmem
cached.c -o rmemcached.o
rmemcached.c: In function âmemcache_connectâ:
rmemcached.c:18: error: âmemcached_return_tâ undeclared (first use in this function)
rmemcached.c:18: error: (Each undeclared identifier is reported only once
rmemcached.c:18: error: for each function it appears in.)
rmemcached.c:18: error: expected â;â before ârcâ
rmemcached.c:22: error: ârcâ undeclared (first use in this function)

Do you think it could just be a version conflict issue?

**Comment by comron** [comment]
This might be a version issue with libmemcached. I haven't used this
project since I started it, so it may be horribly out of date. I ended up
using redis to cache the things I needed, and used the rredis package.

http://cran.r-project.org/web/packages/rredis/index.html

On Wed, Jan 18, 2012 at 1:53 PM, ChappedSky <
reply@reply.github.com

**Comment by dchapsky** [comment]
Thanks, I'll check it out.
